Check coverage in github action.

diff --git a/.github/workflows/ci-per-package.yaml b/.github/workflows/ci-per-package.yaml
--- a/.github/workflows/ci-per-package.yaml
+++ b/.github/workflows/ci-per-package.yaml
@@ -71,3 +71,20 @@ jobs:
           fi
 
       - run: vendor/bin/phpunit
+
+      - name: Enforce PHPUnit code coverage
+        run: |
+          set -x
+          if [ ! -f .coverage ] || [ ! -f build/logs/clover.xml ]; then
+            exit 0
+          fi
+          expected=$(head -n 1 .coverage)
+          line=$(grep -o '<metrics[^>]*>' build/logs/clover.xml | head -1)
+          total=$(echo "$line" | sed -n 's/.* statements="\([0-9]*\)".*/\1/p')
+          covered=$(echo "$line" | sed -n 's/.* coveredstatements="\([0-9]*\)".*/\1/p')
+          percentage=$(echo "$covered / $total * 100" | bc -l)
+          if [ $(echo "$covered * 100 < $expected * $total" | bc) -eq 1  ]; then
+            echo "Fail: Expected at least $expected% coverage, found $percentage% coverage."
+            exit 1
+          fi
+          echo "Pass: Expected at least $expected% coverage, found $percentage% coverage."
